# Generated by Django 4.2 on 2023-04-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Date_of_Birth', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_Number', models.IntegerField()),
                ('Country', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Hobbies', models.CharField(max_length=50)),
            ],
        ),
    ]
